# Generated by Django 4.2.3 on 2023-08-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('SP', 'Спорт'), ('PO', 'Политика'), ('ED', 'Образование'), ('LE', 'Досуг'), ('SB', 'Подписка')], max_length=2, unique=True),
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
