# Generated by Django 4.2.3 on 2023-08-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_category_category_delete_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subscribe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('SP', 'Спорт'), ('PO', 'Политика'), ('ED', 'Образование'), ('LE', 'Досуг')], max_length=2, unique=True),
        ),
    ]
