# Generated by Django 4.2.3 on 2023-09-02 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_subcribenotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcribenotification',
            name='post',
        ),
        migrations.AddField(
            model_name='subcribenotification',
            name='client_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcribenotification',
            name='date',
            field=models.DateField(default=datetime.datetime.utcnow),
        ),
        migrations.AlterField(
            model_name='subcribenotification',
            name='message',
            field=models.TextField(),
        ),
    ]
