# Generated by Django 4.2.3 on 2023-09-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_categorysubscriber_delete_subcribenotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='posts_day_limit',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='author',
            name='posts_on_this_day',
            field=models.IntegerField(default=0),
        ),
    ]
