# Generated by Django 4.2.3 on 2023-09-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_author_posts_day_limit_author_posts_on_this_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='limit_status',
            field=models.BooleanField(default=False),
        ),
    ]
